__source__ = 'https://leetcode.com/problems/find-the-difference/description/'
# https://github.com/kamyu104/LeetCode/blob/master/Python/find-the-difference.py
# Time:  O(n)
# Space: O(1)
#
# Description: Leetcode # 389. Find the Difference
#
# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s
# and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.
#
# Companies
# Google
# Related Topics
# Hash Table Bit Manipulation
# Similar Questions
# Single Number
#
from operator import xor
import unittest
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        return chr(reduce(xor, map(ord, s), 0) ^ reduce(xor, map(ord, t), 0))

class TestMethods(unittest.TestCase):
    def test_Local(self):
        self.assertEqual(1, 1)

if __name__ == '__main__':
    unittest.main()

Java = '''
# Thought:

# 3ms 99.56%
class Solution {
    public char findTheDifference(String s, String t) {
        int cur = 0;
        for (char c : s.toCharArray()) {
            cur ^= c;
        }
        for (char c : t.toCharArray()) {
            cur ^= c;
        }
        return (char) cur;
    }
}

# 4ms 81.36%
class Solution {
    public char findTheDifference(String s, String t) {
        char xor = 0;
        for (char c : s.toCharArray()) {
            xor ^= c;
        }
        for (char c : t.toCharArray()) {
            xor ^= c;
        }
        return xor;
    }
}
'''